### ISSUE TITLE
BOM upload

### ISSUE THREAD

**Issue by samuk** [Twisted-Fields/rp2040-motor-controller#3]
I was curious about getting some boards made up by JLPCB.

I opened the project in Kicad and used this plugin https://github.com/Bouni/kicad-jlcpcb-tools to generate Gerbers & BOM. eg [BOM-RP2040_motor.csv](https://github.com/Twisted-Fields/rp2040-motor-controller/files/8898464/BOM-RP2040_motor.csv)

When I upload these files to JLPCB 56 of the components are not automatically detected.   
![56](https://user-images.githubusercontent.com/400875/173545626-38fb98bb-0c13-4038-b133-11ccba07b105.png)
I guess this plugin may be buggy/incomplete? Is there a better way to do this?

Could you upload a BOM where JLPCB auto-detects all the components?

**Comment by nathmo** [comment]
Something else related to the BOM : would it be possible to mention the approximate total of the BOM on the README.md ? How much does this controller cost ? 10 ? 20 ? 50 ? 100? 200?

**Comment by samuk** [comment]
Posted
